### ISSUE TITLE
chandeleur islands jpg missing

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#100]
http://archive.publiclaboratory.org/gulf-coast/2010-05-09-louisiana-chandeleur/2010-5-9-louisiana-chandeleur.jpg

**Comment by gonzoearth** [comment]
Sorry that's part of the last group that I am uploading

On Mar 19, 2012, at 4:28 PM, Jeffrey Warren
reply@reply.github.com
wrote:

**Comment by gonzoearth** [comment]
http://archive.publiclaboratory.org/gulf-coast/2010-05-09-louisiana-chandeleur/jpg/2010-05-09-louisiana-chandeleur.jpg
