### ISSUE TITLE
Notification of comments on your own research notes

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#153]
We have http://drupal.org/project/subscriptions, what about http://drupal.org/project/notifications

Or, could we install http://drupal.org/project/comment_notify on top of subscriptions?

**Comment by jywarren** [comment]
i'm sorry, it seems we are on notifications, not subscriptions. Oops :-P

**Comment by jywarren** [comment]
I've installed comment_notify to test it out. It should auto-subscribe authors to their own comment feeds, and offer notifications for anyone who comments

**Comment by rjcorwin** [comment]
In the 6.x-4.x branch of notifications_extra you'll get an equivalent of the comment_notify functionality except it integrates with the notifications framework.  The benefit being that users then don't have to manage two separate subscription UIs.  I haven't played around with the subscriptions module much as the notifications module has always had better adoption.  A number of major Drupal Install Profiles use notifications so I can't imagine it's a bad choice over subscriptions.

**Comment by jywarren** [comment]
comment_notify seems to work fine for now. closing and we can revisit if we think we can do better.
