### ISSUE TITLE
cross post research notes and googlegroups

### ISSUE THREAD

**Issue by adamdgriffith** [jywarren/plots#155]
just an idea since if someone looks at a research note on the website, they might miss all the conversations that happen about that topic.  Jeff writes:

I think this might be tough, but I have wanted to do it for a long time. +1 but no clear idea of how to get it done... :-(

Well, it might involve moving off of Google Groups and using a Drupal module called Organic Groups:

http://drupal.org/project/og_mailinglist

Or creating a "forums" area and installing these: http://drupal.org/node/40777

RJ will know more. He had some ideas posted for programming bottleneck, among them attending Drupal events and trying to attract help there. Anyhow if you can, please post the above links/notes to the github issue on mailing list integration, which already exists...

**Comment by jywarren** [comment]
duplicate with both:

https://github.com/jywarren/plots/issues/116

https://github.com/jywarren/plots/issues/12

Not a big deal but do try to look for existing issues before posting.

**Comment by adamdgriffith** [comment]
Oops.  Ok.  Thanks and sorry.
