### ISSUE TITLE
Contributors function not working on the Thermal Flashlight page?

### ISSUE THREAD

**Issue by swylie** [jywarren/plots#156]
When I open the thermal flashlight page the list of contributors and graph of contribution doesn't show up? It would be get to fix immediately as I just directed the Make Blog readers to that page.

**Comment by rjcorwin** [comment]
It looks like it's working now.  Maybe Jeff just fixed it?

## 

RJ Steinert
http://rjsteinert.com

On Fri, May 4, 2012 at 11:26 PM, swylie <
reply@reply.github.com

**Comment by swylie** [comment]
Thanks RJ it turns out there are two very similar pages:

http://publiclaboratory.org/wiki/thermal-camera--Linked to from
http://publiclaboratory.org/tools--this one has the bug

http://publiclaboratory.org/tool/thermal-photography--Linked to from the
tools drop down menu--this one does not.

I've asked Jeff if can eliminate one of them, or have both links direct to
the same page, to avoid this confusion in the future.

On Fri, May 4, 2012 at 11:46 PM, R.J. Steinert <
reply@reply.github.com

**Comment by jywarren** [comment]
Actually there is only one page in the database, but it has 2 names, so shows up at 2 URLs. I reordered them a bit --  and throughout the site, links now say "thermal-photography".

Re: deleting the 2nd name, I didn't want people going to "thermal-camera" to get a "not found" error so you can still see the page there. Over time the "thermal-camera" links should be less and less used, so we can eventually delete that URL alias.
