### ISSUE TITLE
Make adding images to wiki page and tool pages easier?

### ISSUE THREAD

**Issue by swylie** [jywarren/plots#160]
I'd like to be able to add an image of the PLOTS tool development diagram to the tool development wiki page: http://publiclaboratory.org/wiki/tool-development-timeline. Currently it seems like you need a flickr account to do this, can we make it easy to add images here in the same way we can with research notes? I think adding the stage of requiring familiarity with not just our site but also flickr is too much of a threshold for anyone but the really web familiar to cross.  It also has the knock-on effect of making the pages made by those without Flickr accounts or familiar less attractive.

**Comment by jywarren** [comment]
Duplicate with #24, please read that and copy over any relevant info to that issue, thanks!
