### ISSUE TITLE
Gateway time out error when making research notes or adding comments

### ISSUE THREAD

**Issue by swylie** [jywarren/plots#168]
Every time I tried to add a comment or note last week i received an error which read "504 Gateway Time-out". When I checked the notes and comments had been recorded but the error lead me initially to resubmit comments so they appeared twice. I think Scott and others have also had this problem.

**Comment by jywarren** [comment]
I believe this is a dupe with #157, which is surprising as we haven't seen it for a while. Closing and linking over. Will investigate when have a moment.
