### ISSUE TITLE
Pages listing for Research notes on each tool

### ISSUE THREAD

**Issue by swylie** [jywarren/plots#174]
Finding research notes on tools is really getting to be hard because you can't see a list of all of the research notes on a topic or page through them.  You can do this with individual contributers notes, can we make it possible to do this for research notes on each tool? 

See: 
http://publiclaboratory.org/people/warren
here you can page through all of Jeff's notes

it would be great to have the same function at the bottom of each tool page:
http://publiclaboratory.org/notes/thermal-photography

**Comment by mathewlippincott** [comment]
Each keyword will only display one page of recent research notes, which is extremely frustrating and makes browsing research notes essentially impossible.  There are 239 balloon mapping research notes according to the tags listing, but only the latest 18 are visible.  Pagination is needed urgently on the notes aggregation pages:
http://publiclaboratory.org/tags
http://publiclaboratory.org/notes/balloon-mapping

**Comment by jywarren** [comment]
Sara - actually there is a listing at the bottom of each tool page, to the bottom right. We could expand this, and i believe this is one of the major parts of the tool page revision mockups we've posted. (esp. the tabbed mockups).

Mathew - whoa, that seems nuts -- i'm sure this feature used to be there. I'm sure I've used it recently. I dunno what happened, i'm looking into it now.

Are you tagging everything? I'm getting lots and lots of updates. Cool. We don't have a listing of _pages_ per tag, btw, we should add that.

**Comment by jywarren** [comment]
http://publiclaboratory.org/notes/spectrometer?page=1

done

**Comment by mathewlippincott** [comment]
Awesome!  Thanks for fixing that.  Yeah-- I just went back and consistently tagged every photo rig and DIY kite resource.

**Comment by jywarren** [comment]
primitive but usable: http://publiclaboratory.org/pages/balloon-mapping

we could link to this from the tool pages too, not sure where. Should incorporate into our redesign
