### ISSUE TITLE
urgent! mysql error on wiki page

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#179]
http://publiclaboratory.org/wiki/balloon-mapping-materials

error output: https://gist.github.com/4221806

**Comment by gonzoearth** [comment]
Mathew found this error here as well: http://publiclaboratory.org/tool/balloon-mapping 
It seems to only occur when not logged in. I noticed that the normal page content still loads if you scroll all the way down passed the error message.

**Comment by ebarry** [comment]
Ed Keller emailed me about that error two weeks ago, I forwarded it to web
last week but not sure if anyone got it...

**Comment by jywarren** [comment]
with some help from Dan Beavers, this was resolved today.
