### ISSUE TITLE
adding tags to tool pages?

### ISSUE THREAD

**Issue by ebarry** [jywarren/plots#181]
Can we tag a tool page so that it comes up in the same search results as notes related to it? Currently I can't: 

Click button for Tags on a tool page, gives this URL
http://publiclaboratory.org/node/1667/tag
that says only "You have already tagged this post. Your tags:"
but there are no tags

**Comment by jywarren** [comment]
yes, in the old site you can add tags to wiki pages by clicking edit. In the new site it will always be at the bottom, same format.

**Comment by ebarry** [comment]
oh my bad.

On Thu, Jan 31, 2013 at 5:43 PM, Jeffrey Warren notifications@github.comwrote:

> yes, in the old site you can add tags to wiki pages by clicking edit. In
> the new site it will always be at the bottom, same format.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jywarren/plots/issues/181#issuecomment-12970476.

## 

@lizbarry http://twitter.com/lizbarry
