### ISSUE TITLE
Double posts showing up lately in research notes feed

### ISSUE THREAD

**Issue by gonzoearth** [jywarren/plots#182]
Posting this with total ignorance as to the cause. I just have noticed this starting to happenas of late. I doubt that It is from the user posting two separate notes, but rather a new publishing of a new version instead of updating existing content.
![Screen Shot 2013-02-11 at 5 46 09 PM](https://f.cloud.github.com/assets/1051020/147486/2c42c8a0-74b6-11e2-8c8b-f37c237ff5f4.png)

**Comment by jywarren** [comment]
That is a double posting - two separate posts. We should email Dan to find out what happened.

**Comment by gonzoearth** [comment]
I'll keep an eye out and catalog any more sightings here, thanks Jeff!

**Comment by dbeavers** [comment]
I see that it is closed.  I was having problems getting the image loaded and got a couple of error messages if that helps.
