### ISSUE TITLE
Blog page design

### ISSUE THREAD

**Issue by sdosemagen** [jywarren/plots#186]
Current URL is http://publiclab.org/blog/idealab
Need a way to better break up the posts on this page visually.

Liz-- we thought you could help w/ design here?

**Comment by ebarry** [comment]
oh neat -- will this be to collate all blog posts made throughout our
community, or just for IdeaLab?

On Mon, May 13, 2013 at 11:49 AM, Shannon Dosemagen <
notifications@github.com> wrote:

> Current URL is http://publiclab.org/blog/idealab
> Need a way to better break up the posts on this page visually.
> 
> Liz-- we thought you could help w/ design here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jywarren/plots/issues/186
> .

## 

@lizbarry http://twitter.com/lizbarry

**Comment by sdosemagen** [comment]
Its for the whole community, Jeff just set it up with the IdeaLab URL for now, probably will be switching today.

**Comment by jywarren** [comment]
Oops, wrong github project! Can you close and refile at
https://github.com/jywarren/plots2/issues

Thanks.

**Comment by jywarren** [comment]
It's actually for _any_ tag -- you can view any tag at
http://publiclab.org/blog/thermal-flashlight for example
