### ISSUE TITLE
"Gallery" image uploading/embedding feature

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#41]
Preferably drag & drop

**Comment by jywarren** [comment]
For this, we could choose the option:

Position: Manually set in node template by variable $node->node_images

in Content types > edit Note > Node images

and present them in an Unordered List so it shows up in a gallery carousel like RJ's addition here: https://github.com/jywarren/plots/pull/57

**Comment by rjcorwin** [comment]
Alrighty, fairly simple.  A File field called image_gallery using an image widget for the edit screen.   Then under "Display Fields" tab (http://publiclaboratory.org/admin/content/node-type/note/display) I set the full node version of the image gallery field to display as "Lightbox2: thumb -> original".  Added some CSS in node.css and voila. Click on the thumbs below the main image.  http://publiclaboratory.org/admin/content/node-type/note/display

Edit form needs some touchups.  Trying that now.

**Comment by jywarren** [comment]
This is working really well, RJ; several people have uploaded images using the system and it even properly syndicates to the Grassroots Mapping blog. 

Some people are wanting to place images in specific places, which I am inclined to say "too bad" to, as it adds complexity. 

I am removing "node_images" from the wiki pages; perhaps there we should modify the file-attachment system to offer copy-paste <img> tags so people can do more customizable layouts. We already assume that users making wiki pages are more familiar and comfortable with the site.

**Comment by jywarren** [comment]
Galleries are completed, so i'm closing this; the broader question of whether we want a site-wide easier image uploading system seems still to be open (especially for wiki pages, which the Gallery feature does not address, yet) and I'll point that over to #24
