### ISSUE TITLE
fullscreen openlayers viewer broken

### ISSUE THREAD

**Issue by gonzoearth** [jywarren/plots#62]
-archive-
just broke with todays changes

**Comment by jywarren** [comment]
i believe this is resolved.

**Comment by gonzoearth** [comment]
Awesome, I am looking at it now and it looks great. just those pesky tile
errors with certain zoom levels when you explore around and toggle related
maps (issue #61)

On Wed, Feb 15, 2012 at 11:15 AM, Jeffrey Warren <
reply@reply.github.com
