### ISSUE TITLE
Better spam protection

### ISSUE THREAD

**Issue by rjcorwin** [jywarren/plots#66]
This morning around 2am a spammer got through and make a Wiki post.  I deleted the account.  

@jywarren Has this been a problem in the past?

**Comment by jywarren** [comment]
i've seen maybe 2 others over the past 6 months. I banned those users, but
wasn't sure how they got in. There are a lot of spammy users (i'm inclined
to delete anyone who's never _accessed_ the site, maybe) but almost none of
them create content.

jeff

On Mon, Jan 30, 2012 at 5:22 AM, R.J. Steinert <
reply@reply.github.com

**Comment by jywarren** [comment]
I suggested a larger group of moderators on the team mailing list. I'm looking at if there is a more efficient way to block users rather than actually editing their profile. (i usually do it from http://publiclaboratory.org/user/527/edit)

we could do what Google Groups offers and moderate the first post someone makes, no matter what... 

or perhaps if they signed up without an invite (we don't do invites yet but if we ever did it might bypass this extra check)

**Comment by jywarren** [comment]
I found this, may be helpful: http://drupal.org/project/ban_unpublish 

batch operation to thoroughly kick off, unpublish, remove comments, etc for a given user.

**Comment by jywarren** [comment]
I created a "moderator" role which can submit spam, edit user profiles, and delete notes and pages. I did not allow them to edit notes, though maybe I should... I think it's good to avoid the temptation to actually edit someone else's work -- if it's a problem, just unpublish it and ask them to change it?

http://publiclaboratory.org/admin/user/permissions/5

feel free to change how this is set up...

**Comment by jywarren** [comment]
starting to make a "how to moderate" page so we can get more moderators. sorry for so many comments

http://publiclaboratory.org/wiki/moderators

**Comment by rjcorwin** [comment]
I haven't looked at it for over a year now but I remember the Mollom module offering a lot of UI to for managing a spam killing workflow.  It also has the option of hiring their AI to automatically flag/can items.  I'd lend a hand right now but GreenLink is pushing for a launch on Monday. 

http://drupal.org/project/mollom

**Comment by jywarren** [comment]
http://publiclaboratory.org/wiki/moderators outlines moderator abilities and shows how to do moderation tasks.

**Comment by jywarren** [comment]
New type of spam today; by user "Anonymous" ...? Bump priority of installing Mollum, i guess. Could be related to security updates?

**Comment by rjcorwin** [comment]
That sounds weird.  Let's go over this in person tomorrow if you catch me at the ship.

**Comment by jywarren** [comment]
Is there a "usual" way to lock nodes that get spammed a lot, to stop vandalism? This page is getting hit probably because its send as a link in the registration confirmation email: http://publiclaboratory.org/wiki/getting-started

**Comment by rjcorwin** [comment]
That's a good question.  There is a lock feature for nodes built into Drupal to prevent collisions.

user1 clicks edit on node1
user2 clicks edit on node1
user2 clicks saves node1
user1 clicks save on node1 
user1 is notified that the node was edited while they were editing and user1 is returned to node1 with their version still in the edit form

So I suppose we could specify nodes that just always end where user1 ended in the above use case.  The only problem I see with that is then no one can edit that node ever again (unless we had some kind of explicit logic checking for User ID or Role).  So... Now that I think of it I think that the Nodeaccess module might give us what we want.

http://drupal.org/project/nodeaccess

"Users with the 'grant node permissions' permission will have a grant tab on node pages which allows them to grant access to that node by user or role. Administrators can set default access controls per content type, and also define which roles are available to grant permissions to on the node grants tab."

So the default node access scheme for Wiki pages would be to allow everyone to edit and view, the Admin role would have the 'grant node permissions' permission, and when a user with the Admin role wanted to lock a node they would click the "grant tab" on that node and remove the edit permissions for the "authenticated user" role.

**Comment by adamdgriffith** [comment]
FYI, I just deleted three spam posts as a moderator.  go me.  I did not delete their profiles  - publicc and xiaoyu77 - but I did change them to BLOCKED instead of ACTIVE.  the posts related to "cheap NHL"  "baby girl" and "cheap NFL"  Don't they do any research on demographics?  Jeff fell asleep at a NFL game.

**Comment by jywarren** [comment]
whoa, that was weird... you just "spammed" the github issue... :-)

thanks! i banned publicc, looks like you'd already banned xiaoyu77. Or maybe we did it at the same time.

if I have a chance today i'll install Mollom

**Comment by adamdgriffith** [comment]
geez.  that's was terrible.  inadvertent spam.  sorry if you all got those notifications.  the page wasn't working.

**Comment by jywarren** [comment]
Mollom seems to be working, closing.

**Comment by jywarren** [comment]
May be some lingering issues here on false positives, both in Akismet and Mollom -- Chris F has been getting a lot of his posts moderated. I'd like to be able to exempt one of the following options:
- users who have posted before (non-first-time)
- users who are added to a "nomoderation" role which we could simply batch- assign to regular users?
- users who register using an invite code

I haven't found much info on these possibilities, just taking note that we'd like to be able to do this.

**Comment by jywarren** [comment]
False positives and negatives (chris F's posts being jailed a lot) frustrated me, so I made a new user role called "unmoderated" which auto-skips any kind of spam moderation. I added Chris to this role and anyone who's posted anything before ought to be added -- having published before is a good metric for not being a spammer, currently...

so we can look into automating that -- perhaps the role could be added at the moment a first-time poster's content is approved, or just by putting an easy button on everyone's profiles which is only visible to moderators... but anyways it's a step in the right direction.

**Comment by jywarren** [comment]
After feedback that spam on the RSS feed is really annoying... reading this for ideas: http://gerardmcgarry.com/blog/drupal-question-moderating-content-new-users-a-site

I cranked up the sensitivity, reduced "bypass" loopholes, and added a lot of spammy words to the blacklist. Idea being that we just stop all spam at all costs, and use the new "unmoderated" role to whitelist anyone we know is OK... with a liberal sprinkling of email notifications using the Rules module.

**Comment by jywarren** [comment]
OK, I was unable to get the following code to work, so I just set up a Rule that saving a wiki page will trigger unpublishing and moderation if you are not admin, staff, moderators, or "unmoderated" roles. Most of our spam is in wiki pages right now so let's see how that goes. 

We can create more rules that easily categorize people as "unmoderated" so they're never bothered by spam moderation again.

Conditional code that didn't work (trying to test if it's a user's first post):

```
<?php $sql = "SELECT count(nid) FROM node WHERE type = 'note' AND status <> 0 AND uid = '".$user->uid."'";
$count = db_result(db_query(db_rewrite_sql($sql), $src));
return $count == 0; ?>
```
