### ISSUE TITLE
editing area not appearing correctly in Firefox

### ISSUE THREAD

**Issue by sdosemagen** [jywarren/plots#73]
In the edit function on all pages (Firefox), the side boxes are overlaying on the text edit box (see picture I emailed).

**Comment by jywarren** [comment]
i couldn't duplicate in my own firefox... what version # are you using?

On Thu, Feb 9, 2012 at 5:11 PM, sdosemagen
reply@reply.github.com
wrote:

**Comment by sdosemagen** [comment]
10.0 firefox and Liz was using chrome and got the same thing 

Shannon Dosemagen
504.239.4642

**Comment by jywarren** [comment]
oh i get it - this is the rich text editor. OK, should be able to fix it monday.

On Sat, Feb 11, 2012 at 9:23 PM, sdosemagen
reply@reply.github.com
wrote:

> 10.0 firefox and Liz was using chrome and got the same thing
> 
> Shannon Dosemagen
> 504.239.4642
>
