### ISSUE TITLE
Mapmill image not importing

### ISSUE THREAD

**Issue by sdosemagen** [jywarren/plots#75]
Does Mapmill go here as well or just PLOTS site- one of the images in the most recent Gowanus set is giving us an error message (sorry this image failed to import) when we try and export to knitter, took a screen shot that we can send

**Comment by jywarren** [comment]
thanks, will check on Monday. Yes, this should go to
https://github.com/jywarren/mapmill/issues/

On Sat, Feb 11, 2012 at 7:00 PM, sdosemagen
reply@reply.github.com
wrote:
