### ISSUE TITLE
mismatch/newly discovered data in UC Davis raw image count for 2011-11-21

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#78]
I found a folder in the mapmill inbox for UC Davis and backed it up but wasn't able to figure out if it's duplicate or a new unarchived set. The one currently in the archive is:

```
warren@durandal:$ count ~/sites/archive.publiclaboratory.org/davis/2011-11-21-california-davis-ucdavis-occupy/raw/
304
```

including IMG_6538.JPG through IMG_8260.JPG

vs the one I just found:

```
warren@durandal:$ count ~/sites/archive.publiclaboratory.org/davis/2011-11-21-california-davis-ucdavis-occupy/raw-2/2011-11-21-california-ucdavis-occupy/
816
```

including IMG_5023.JPG through IMG_5863.JPG

What's up?

**Comment by gonzoearth** [comment]
raw and raw-2 are two separate SD cards that I swapped when we brought the
balloon down for a moment during the flight. I think I deleted the black
shots while the phone was on the ground and that makes up the gap
in between the two sets. I am looking locally and I have the same 2 folders.

On Tue, Feb 14, 2012 at 12:26 PM, Jeffrey Warren <
reply@reply.github.com

**Comment by jywarren** [comment]
this was resolved, no?

**Comment by gonzoearth** [comment]
yep
