### ISSUE TITLE
fullscreen version of maps in archive, esp. for embedding and mobile device use

### ISSUE THREAD

**Issue by jywarren** [jywarren/plots#79]
using new openlayers 2.11 or leaflet...

**Comment by jywarren** [comment]
Trying to get this to work at:

http://publiclaboratory.org/map/gowanus-brooklyn-ny-ir/2012-2-13?fullscreen=true

```
function phptemplate_preprocess_node(&$vars) {
  if (module_exists('path')) {
    if ($_GET['fullscreen'] == "true") {
       $vars['template_files'][] = 'node-map-fullscreen';
    }
  }
}
```

**Comment by jywarren** [comment]
Basing this on a combination of 

http://drupal.org/node/117491
http://drupal.org/node/139766 (for pages, but has Drupal 5/6 variants)

Not getting it to work though.

**Comment by jywarren** [comment]
http://dev.openlayers.org/releases/OpenLayers-2.11/examples/mobile.html shows the OpenLayers 2.11 mobile interface example

**Comment by jywarren** [comment]
test: http://archive.publiclaboratory.org/download/gowanus-leaflet.html

**Comment by jywarren** [comment]
http://archive.publiclaboratory.org/leaflet/index2.html?tms=http://mapknitter.org/tms/lone-rock-pond/&lon=-73.0733&lat=43.96055&zoom=18

Try that! If it's no slower than this:

http://archive.publiclaboratory.org/leaflet/?tms=http://mapknitter.org/tms/lone-rock-pond/&lon=-73.0733&lat=43.96055&zoom=18

then I think we're ready to go with this. I can add it to archive pages as the embed code, and also to MapKnitter, actually.

**Comment by gonzoearth** [comment]
its fast! (the top link)

**Comment by jywarren** [comment]
haven't been able to get it to show as default yet. more soon.

**Comment by gonzoearth** [comment]
one bonus feature might be a button for: zoom to fit/refresh

**Comment by jywarren** [comment]
Ok, google by default is working. Ill be adding embed codes to plots and
mapknitter soon.
On Feb 23, 2012 1:32 PM, "stewart long" <
reply@reply.github.com>
wrote:

**Comment by jywarren** [comment]
Resolved with addition of embed codes in map pages; fork of embed iframe code at: https://github.com/jywarren/plots-leaflet-viewer
