### ISSUE TITLE
fake research notes are spam

### ISSUE THREAD

**Issue by adamdgriffith** [jywarren/plots#81]
In the last 24 hours, it looks as if 3 fake research notes have gotten through our security.  How can they get past captcha?  Do the have profiles?

http://publiclaboratory.org/notes/sinian/2-18-2012/true-religion-jeans-have-uniquely

**Comment by jywarren** [comment]
duplicate of https://github.com/jywarren/plots/issues/66

please join that thread if interested

**Comment by adamdgriffith** [comment]
Thx.  Did you combine them?

**Comment by jywarren** [comment]
There's no formal way to merge requests, so usually i close the newer one,
copy over relevant extra info, and link to the older one, as I did here.
I'll add you as a moderator shortly.

On Sat, Feb 18, 2012 at 3:21 PM, adamdgriffith <
reply@reply.github.com

> wrote:
> 
> Thx.  Did you combine them?
>

**Comment by jywarren** [comment]
And btw i think you have to go to the bottom of the older issue ticket and click on "enable notifications" to get email updates.

**Comment by adamdgriffith** [comment]
thanks, Jeff.

On Sun, Feb 19, 2012 at 12:30 PM, Jeffrey Warren <
reply@reply.github.com

> wrote:
> 
> There's no formal way to merge requests, so usually i close the newer one,
> copy over relevant extra info, and link to the older one, as I did here.
> I'll add you as a moderator shortly.
> 
> On Sat, Feb 18, 2012 at 3:21 PM, adamdgriffith <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Thx.  Did you combine them?
> > 
> > On Feb 18, 2012, at 9:12 AM, Jeffrey Warrenreply@reply.github.com
> > wrote:
> > 
> > > duplicate of https://github.com/jywarren/plots/issues/66
> > > 
> > > please join that thread if interested
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/jywarren/plots/issues/81#issuecomment-4034268
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jywarren/plots/issues/81#issuecomment-4036998
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jywarren/plots/issues/81#issuecomment-4043515

## 

Adam Griffith
Director of Science and Coastal Environments
publiclaboratory.org
828.321.2326

**Comment by oeon** [comment]
back, http://publiclaboratory.org/notes/rlpolo/4-16-2012/ralph-lauren-polo-shirts-are-supplying-related-fashionable-men

**Comment by jywarren** [comment]
yeah this week i plan to install a more advanced spam catching system.
These are real users, so it has to be a content-filter based spam filter,
not just a RECAPTCHA. Fingers crossed.

On Mon, Apr 16, 2012 at 11:34 AM, Joe Larson <
reply@reply.github.com
