### ISSUE TITLE
spectrometry_kit app quits under Mac OS X Snow Leopard

### ISSUE THREAD

**Issue by parsci** [jywarren/plots#94]
When launching spectrometry_kit.app under Mac OS X 10.6.8, the app unexpectedly quits after about 12s. Only a grey screen is apparent (no menus), although the webcam ON indicator illuminates briefly.

**Comment by jywarren** [comment]
Thanks for the issue. Just want to copy in my response from http://publiclaboratory.org/wiki/spectral-workbench-help

> If you see a grey screen, does a your webcam light up for a moment? There is a bug where a popup window asks you to choose a camera, but it can't come to the front because the app is fullscreen. You might try apple-tab once you see the green light come on.

**Comment by jywarren** [comment]
Oh, wait - i'm sorry Parsci, can you refile under the Spectral Workbench project, please? I can repost for you if you like.

https://github.com/jywarren/spectral-workbench/issues/new
