### ISSUE TITLE
Change "PLOTS members who have contributed research Notes" to include Wiki work

### ISSUE THREAD

**Issue by mathewlippincott** [jywarren/plots#95]
I'm not sure how to quantify wiki updates, but I'd like to see wiki updates included in users tool contributions.  I've done a huge amount of work on the balloon mapping wiki pages, but haven't committed that many research notes, and wish that was reflected.

**Comment by jywarren** [comment]
Thanks for creating the issue. RJ and I have been talking about this and it has always been the intent to add this. I'll see what I can do; i think the first time I tried i struggled a bit with it because technically they are "revisions" not nodes.

**Comment by jywarren** [comment]
ok, seem to have it working! Nice-- before/after:

<a href="http://www.flickr.com/photos/jeffreywarren/6819402594/" title="contributors-of-notes by jeferonix, on Flickr"><img src="http://farm8.staticflickr.com/7069/6819402594_afa63037d8.jpg" width="199" height="488" alt="contributors-of-notes"></a>

<a href="http://www.flickr.com/photos/jeffreywarren/6819402596/" title="contributors-of-notes-and-revisions by jeferonix, on Flickr"><img src="http://farm8.staticflickr.com/7059/6819402596_7d2eeffaa0.jpg" width="178" height="500" alt="contributors-of-notes-and-revisions"></a>
